# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse200(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, hello_user: str=None):  # noqa: E501
        """InlineResponse200 - a model defined in Swagger

        :param hello_user: The hello_user of this InlineResponse200.  # noqa: E501
        :type hello_user: str
        """
        self.swagger_types = {
            'hello_user': str
        }

        self.attribute_map = {
            'hello_user': 'HelloUser'
        }
        self._hello_user = hello_user

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.  # noqa: E501
        :rtype: InlineResponse200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def hello_user(self) -> str:
        """Gets the hello_user of this InlineResponse200.


        :return: The hello_user of this InlineResponse200.
        :rtype: str
        """
        return self._hello_user

    @hello_user.setter
    def hello_user(self, hello_user: str):
        """Sets the hello_user of this InlineResponse200.


        :param hello_user: The hello_user of this InlineResponse200.
        :type hello_user: str
        """

        self._hello_user = hello_user
